/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : PDF2TEXT
 #	author : miyako
 #	2015/08/03
 #
 # --------------------------------------------------------------------------------*/

#include <assert.h>
#include <stdlib.h>
#include <glib.h>
#include <poppler.h>
#include <poppler-document.h>
#include <poppler-page.h>
#include <cairo.h>
#include <cairo-svg.h>
#include <stdio.h>
#include <string.h>

typedef PA_long32 method_id_t;

// --- Text
void PDF_Get_text(sLONG_PTR *pResult, PackagePtr pParams);
